<a href="/admin/showAllOrders" class = 'btn btn-primary d-flex float-right mx-2'>Show All Orders</a>
<a href="/admin/showAllUsers" class = 'btn btn-primary d-flex float-right'>Show All Users</a>
<h3 class='text-center'>List of All books</h3>
<div class="row m-2">
    <?php
    $data = json_decode($data, true);
    foreach ($data as $key => $value) {
        echo "<div class = 'm-2 col-5'>
             <div class=\"card shadow text-center\">
                <div class=\"card-body\">
                  <h3 class=\"h5 card-title\"><strong>Name : </strong>$value[title]</h3>
                  <h3 class=\"h5 card-title\"><strong>Price : </strong>$value[price]</h3>
                  <p class=\"card-text\"><strong>ID : </strong> $value[bid]</p>
                </div>
                <div class=\"card-footer bg-white border-0\">
                </div>
              </div>
              </div>";
    }
    ?>
</div>
