<a href='/book/' class='btn btn-primary d-flex float-right'>Home</a>
<div class="row mt-5" >
    <div class="col-12 mt-5">
        <div class="card shadow p-4">
            <div class="card-header border-0 bg-white text-center pb-0">
                <h1 class="mb-0 h4">Add New Book</h1>
            </div>
            <div class="card-body">
                <form action="/book/addBook" method="post">
                    <!-- Form -->
                    <div class="form-group mb-4">
                        <label for="exampleInputEmailCard3">Title</label>
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Book Title" name='title'>
                        </div>
                    </div>

                    <div class="form-group mb-4">
                        <label for="exampleInputEmailCard3">Price</label>
                        <div class="input-group">
                            <input type="number" class="form-control" placeholder="Book Price" name='price'>
                        </div>
                    </div>

                    <div class="form-group mb-4">
                        <label for="exampleInputEmailCard3">Stock</label>
                        <div class="input-group">
                            <input type="number" class="form-control" placeholder="Stock" name='stock'>
                        </div>
                    </div>

                    <div class="d-grid">
                        <button type="submit" class="btn btn-success">Add book</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
