<a href='/book/' class='btn btn-primary d-flex float-right'>Home</a>
<h3 class='text-center'>My Orders</h3>
<div class="row m-2">
    <?php
    $data = json_decode($data, true);
    foreach ($data as $key => $value) {
        echo "<div class = 'm-2 col-5'>
             <div class=\"card shadow text-center\">
                <div class=\"card-body\">
                  <h3 class=\"h5 card-title\"><strong>Order ID : </strong>$value[oid]</h3>
                  <h3 class=\"h5 card-title\"><strong>Quantity : </strong>$value[quantity]</h3>
                  <p class=\"card-text\"><strong>Book ID : </strong> $value[bid]</p>
                </div>
                <div class=\"card-footer bg-white border-0\">
                </div>
              </div>
              </div>";
    }
    ?>
</div>
