<section class="h-100 h-custom" style="background-color: #8fc4b7;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-8 col-xl-6">
                <div class="card rounded-3">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/img3.webp" class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;" alt="Sample photo">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Registration Info</h3>
                        <form class="px-md-2" action="/index/register" method="POST">
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example1q" class="form-control" name='name' />
                                <label class="form-label" for="form3Example1q">Name</label>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example1q" class="form-control" name='email' />
                                <label class="form-label" for="form3Example1q">Email</label>
                            </div>
                            <div class="form-outline mb-4">
                                <input type="text" id="form3Example1q" class="form-control" name='password' />
                                <label class="form-label" for="form3Example1q">Password</label>
                            </div>
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    Role:
                                    <select class="select" name='role'>
                                        <option value="user" default>User</option>
                                        <option value="admin">Admin</option>
                                    </select>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-success btn-lg mb-1 mx-4">Sign Up</button>
                            <a href="/index/login" class='btn btn-primary btn-lg mb-1 mx-5'>Login Instead</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
